stages:
  # - build
  - deploy

# build:
#   stage: build
#   image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
#   script:
#     - pwd
#     - ls
#     - composer install --prefer-dist --no-ansi --no-interaction --no-progress
#     - cp .env.example .env
#     - php artisan key:generate
#     - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr

deploy_production:
  stage: deploy
  image: ubuntu:latest
  only:
    - master
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ls
    - echo "here"
    - ssh
    - sshpass -p $DEPLOY_PASS ssh $DEPLOY_USER@$DEPLOY_URL

