stages:
  - build
  - deploy

build:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  only:
    - merge_requests
    - master
  script:
    - pwd
    - ls
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr

build_notify:
  stage: build
  image: ubuntu:latest
  only:
    - merge_requests
  script:
    - curl -X POST -H $CURL_HEADERS --data $BUILD_BODY https://hooks.slack.com/services/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

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - pwd
    - whoami
    - cd /home/$DEPLOY_USER/fatbooty/
    - sudo bash deploy.sh

deploy_notify:
  stage: build
  image: ubuntu:latest
  only:
    - master
  script:
    - curl -X POST -H $CURL_HEADERS --data $DEPLOY_BODY https://hooks.slack.com/services/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
